// Generated by nuxi
/// <reference types="@nuxtjs/tailwindcss" />
/// <reference types="@nuxtjs/google-fonts" />
/// <reference types="@nuxtjs/color-mode" />
/// <reference types="nuxt-swiper" />
/// <reference types="@nuxtjs/html-validator" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="nuxt" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference types="swiper/vue" />
/// <reference path="components.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
